export const projectItems = [
    {
        title: 'TransLoc Redesign',
        url: 'transloc-redesign',
        img: require('./assets/projects/transloc/home-card-mockup-transloc.png'),
        desc: 'Reimagining a more accessible way to use public transportation',
        timeLength: '12 Weeks, ',
        timeline: 'Sep - Dec 2021',
        team: ['3 UX Designers'],
        role: ['User Flow Research', 'Core Feature Ideation', 'Hi-Fi Prototyping'],
        location: 'Charlottesville, VA',
        problem: 'Transloc is a public transportation app with ridesharing, bus schedules, and live mapped bus routes widely used in Charlottesville, Virginia.',
        question: 'How can we improve the interface to help the community reach their destinations efficiently?',
        process: '',
        research: '',
        researchFindings: '',
        researchInsights: '',
    },
    {
        title: 'Study Buddy',
        url: 'study-buddy',
        // img: require('./assets/projects/transloc/home-card-mockup-transloc.png'),
        desc: 'Get Good Grades with Even Better Friends to Study With',
        timeLength: '15 Weeks, ',
        timeline: 'Jan - May 2022',
        team: ['Scrum Master', 'Dev Ops Manager', 'UX Designer', 'Testing Manager', 'Requirements Manager'],
        role: ['UX Designer', 'Core Feature Development', 'Lo-Fi and Hi-Fi Designs'],
        location: 'Charlottesville, VA',
        problem: 'Students struggle to find other students in similar classes to study with.',
        question: 'How can we connect students with similar classes to each other?',
        process: '',
        research: '',
        researchFindings: '',
        researchInsights: '',
    },
    {
        title: 'Study Space',
        url: 'study-space',
        // img: require('./assets/projects/transloc/home-card-mockup-transloc.png'),
        desc: 'Find your best study space on Grounds',
        timeLength: '18 Weeks, ',
        timeline: 'May - September 2023',
        team: ['UX Designer'],
        role: ['User Research', 'Core Feature Ideation', 'Wireframing','Hi-Fi Prototyping'],
        location: 'Charlottesville, VA',
        problem: 'There are many study spaces on grounds with no centralized resource abut them. Students struggle to find one that suits their needs best.',
        question: 'How can we help students find the best study space for their studying needs?',
        process: '',
        research: '',
        researchFindings: '',
        researchInsights: '',
    },
];